<?php
$menu['menu360'] = array(
    array('360000', '블로그자동화', G5_ADMIN_URL . '/blog/project_list.php', 'blog'),
    array('360100', '광고주관리', G5_ADMIN_URL . '/blog/advertiser_list.php', 'blog_advertiser'),
    array('361100', '광고주 계정관리', G5_ADMIN_URL . '/blog/advertiser_account_list.php', 'blog_advertiser_account'),
    array('361110', 'SNS/채널 앱 설정', G5_ADMIN_URL . '/blog/channel_app_list.php', 'blog_channel_app'),
    array('360200', '발행사이트관리', G5_ADMIN_URL . '/blog/site_list.php', 'blog_site'),
    array('360300', 'AI 공급자설정', G5_ADMIN_URL . '/blog/ai_provider_list.php', 'blog_ai_provider'),
    array('360400', '콘텐츠 프로젝트', G5_ADMIN_URL . '/blog/project_list.php', 'blog_project'),
    array('360700', '예약 발행 관리', G5_ADMIN_URL . '/blog/publish_job_list.php', 'blog_publish_job'),
    array('360800', '이미지 라이브러리', G5_ADMIN_URL . '/blog/image_list.php', 'blog_image'),
    array('360900', '테이블 설치', G5_ADMIN_URL . '/blog/install_form.php', 'blog_install'),
    array('361000', '보고서 대시보드', G5_ADMIN_URL . '/blog/report_dashboard.php', 'blog_report'),
    array('361000', '일간 발행 보고서', G5_ADMIN_URL . '/blog/report_daily.php', 'blog_report_daily'),
    array('361010', '주간 운영 보고서', G5_ADMIN_URL . '/blog/report_weekly.php', 'blog_report_weekly'),
    array('361020', '월간 광고주 보고서', G5_ADMIN_URL . '/blog/report_monthly_adv.php', 'blog_report_monthly'),
    array('361000', '사이트별 발행 통계', G5_ADMIN_URL . '/blog/report_site.php', 'blog_report_site'),
    array('361030', '콘텐츠 성과 기록', G5_ADMIN_URL . '/blog/report_performance.php', 'blog_report_perf'),
    array('361000', '성공·실패 통계', G5_ADMIN_URL . '/blog/report_stats.php', 'blog_report_stats'),
);
